# Generated by Django 5.2 on 2025-06-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("card", "Онлайн картой"),
                            ("someone", "Онлайн со случайного чужого счёта"),
                        ],
                        default="card",
                        max_length=10,
                        verbose_name="Тип платежа",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер карты/счёта"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Имя владельца",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Месяц"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Год"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="CVV код"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает обработки"),
                            ("success", "Успешно"),
                            ("failed", "Неуспешно"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
