# Generated by Django 5.2 on 2025-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["product", "is_active", "dateFrom", "dateTo"],
                name="catalog_sal_product_ff459e_idx",
            ),
        ),
    ]
